require('./bootstrap');
import 'datatables.net';
import 'datatables.net-dt';
import 'datatables.net-fixedcolumns-dt';
import 'datatables.net-fixedheader-dt';
import 'datatables.net-responsive-dt';
import 'datatables.net-searchbuilder-dt';
import 'datatables.net-datetime';
import 'datatables.net-scroller-dt';
import 'datatables.net-rowgroup-dt';
import 'datatables.net-buttons-dt';
import jsZip from 'jszip';
import 'datatables.net-buttons/js/buttons.colVis.min';
import 'datatables.net-buttons/js/dataTables.buttons.min';
import 'datatables.net-buttons/js/buttons.flash.min';
import 'datatables.net-buttons/js/buttons.html5.min';
import 'datatables.net-buttons/js/buttons.print.min';
import 'holderjs';
import 'select2';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import download from 'downloadjs';

window.JSZip = jsZip;
window.PDFDocument = PDFDocument;
window.StandardFonts = StandardFonts;
window.rgb = rgb;
window.download = download;